//
//  ProfileSettingsPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 2/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class ProfileSettingsPresenter {

    // MARK: - Private properties -

    private unowned let view: ProfileSettingsViewInterface
    private let interactor: ProfileSettingsInteractorInterface
    private let wireframe: ProfileSettingsWireframeInterface

    // MARK: - Lifecycle -

    init(view: ProfileSettingsViewInterface, interactor: ProfileSettingsInteractorInterface, wireframe: ProfileSettingsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ProfileSettingsPresenter: ProfileSettingsPresenterInterface {
    func pressedLogOut() {
        interactor.logOut()
    }
    func loggedOut() {
        wireframe.transitionToLogOut()
    }

}
