//
//  ProfileSettingsWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 2/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class ProfileSettingsWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ProfileSettingsViewController()
        super.init(viewController: moduleViewController)

        let interactor = ProfileSettingsInteractor()
        let presenter = ProfileSettingsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ProfileSettingsWireframe: ProfileSettingsWireframeInterface {
    func transitionToLogOut() {
        UserDefaults.standard.set(false, forKey: "launchedBefore")
        UIApplication.shared.keyWindow?.rootViewController = TabBarWireframe.init(isFirstTime: true).viewController

    }
}
