//
//  ProfileSettingsInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 2/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileSettingsWireframeInterface: WireframeInterface {
    func transitionToLogOut()
}

protocol ProfileSettingsViewInterface: ViewInterface {
}

protocol ProfileSettingsPresenterInterface: PresenterInterface {
    func pressedLogOut()
    func loggedOut()
}

protocol ProfileSettingsInteractorInterface: InteractorInterface {
    func logOut()
}
