//
//  ProfileSettingsInteractor.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 2/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class ProfileSettingsInteractor {
    weak var presenter: ProfileSettingsPresenter?
}

// MARK: - Extensions -

extension ProfileSettingsInteractor: ProfileSettingsInteractorInterface {
    func logOut() {
        presenter?.loggedOut()
    }

}
