//
//  TabBarPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 11.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TabBarPresenter {

    // MARK: - Private properties -

    private unowned let view: TabBarViewInterface
    private let interactor: TabBarInteractorInterface
    private let wireframe: TabBarWireframeInterface

    // MARK: - Lifecycle -

    init(view: TabBarViewInterface, interactor: TabBarInteractorInterface, wireframe: TabBarWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension TabBarPresenter: TabBarPresenterInterface {
    func showLogin() {
        wireframe.transitionToLogIn()
    }
}
