//
//  TabBarViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 11.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Firebase

final class TabBarViewController: UITabBarController, UITabBarControllerDelegate {
    
    
    // MARK: - Public properties -
    
    var presenter: TabBarPresenterInterface!
    
    var titles = ["Home","Search", "Post", "Liked", "Profile"]
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        delegate = self
        tabBar.backgroundColor = .white
       
    }
    
    override func viewDidAppear(_ animated: Bool) {
        for i in 0...titles.count - 1 {
            viewControllers?[i].title = titles[i]
        }
    }
    
    func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        print("Should select viewController: \(viewController.title ?? "") ?")
        return true;
    }
}

// MARK: - Extensions -

extension TabBarViewController: TabBarViewInterface {
}
