//
//  EditProfileItemInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 26.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EditProfileItemWireframeInterface: WireframeInterface {
    func viewDisappeared()
}

protocol EditProfileItemViewInterface: ViewInterface {
    func setCurrentInformation(labelText: String, information: String)
}

protocol EditProfileItemPresenterInterface: PresenterInterface {
    func determineLayout()
    func pressedDone(with text: String)
    func pressedCancel()
}

protocol EditProfileItemInteractorInterface: InteractorInterface {
}
