//
//  EditProfileItemPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 26.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

protocol EditProfileItemDelegate: AnyObject {
    func recieveNewData(updatedUserInformation: UserInformation)
}

class EditProfileItemPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: EditProfileItemViewInterface
    private let interactor: EditProfileItemInteractorInterface
    private let wireframe: EditProfileItemWireframeInterface
    var delegate: EditProfileItemDelegate?
    var isChangingUsername = false
    var userInformation: UserInformation?
    var currentCase: FormItems?
    
    // MARK: - Lifecycle -
    
    init(view: EditProfileItemViewInterface, interactor: EditProfileItemInteractorInterface, wireframe: EditProfileItemWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension EditProfileItemPresenter: EditProfileItemPresenterInterface {
    func viewLoaded() {
        switch currentCase {
        case .name:
            view.setCurrentInformation(labelText: currentCase!.rawValue, information: userInformation?.name ?? "none", count: 25)
        case .username:
            isChangingUsername = true
            view.setChangeUserName(username: userInformation?.username ?? "none", count: 25)
        case .occupation:
            view.setCurrentInformation(labelText: currentCase!.rawValue, information: userInformation?.occupation ?? "none", count: 50)
        case .bio:
            view.setCurrentInformation(labelText: currentCase!.rawValue, information: userInformation?.bio ?? "none", count: 150)
        case .nothing:
            fatalError()
        case .none:
            fatalError()
        }
        
    }
    func pressedDone(with text: String){
        if isChangingUsername {
            interactor.checkUsername(username: text)
            isChangingUsername = false
        } else {
            switch currentCase {
            case .username:
                userInformation?.username = text
            case .bio:
                userInformation?.bio = text
            case .occupation:
                userInformation?.occupation = text
            case .name:
                userInformation?.name = text
            case .nothing:
                fatalError()
            case .none:
                fatalError()
            }
            
            delegate?.recieveNewData(updatedUserInformation: userInformation!)
            wireframe.viewDisappeared()
        }
    }
    
    func pressedCancel() {
        wireframe.viewDisappeared()
    }
    
    func pressedDoneForUsername(username: String) {
        interactor.checkUsername(username: username)
    }
    
}
