//
//  EditProfileItemInteractor.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 26.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Firebase

class EditProfileItemInteractor {
    weak var presenter: EditProfileItemPresenter!
    var userService: UserService?
}

// MARK: - Extensions -

extension EditProfileItemInteractor: EditProfileItemInteractorInterface {
    func checkUsername(username: String) {
        userService?.checkUsername(username: username){ [weak self] (bool) in
            if !bool {
                self?.presenter.pressedDone(with: username)
            } else {
                self?.presenter.pressedCancel()

            }
        }
    }
}
