//
//  EditProfileItemViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 26.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit



final class EditProfileItemViewController: UIViewController, UITextFieldDelegate {
    
    // MARK: - Public properties -
    weak var delegate: EditProfileItemDelegate?
    var presenter: EditProfileItemPresenterInterface!
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        setupNavigationBar()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        presenter.determineLayout()
    }
    
    func setupNavigationBar() {
        navigationItem.leftBarButtonItem = UIBarButtonItem(title: NSLocalizedString("Cancel", comment: "Cancel"), style: .plain, target: self, action: #selector(EditProfileItemViewController.pressCancel))
        navigationItem.rightBarButtonItem = UIBarButtonItem(title: NSLocalizedString("Done", comment: "Done"), style: .plain, target: self, action: #selector(EditProfileItemViewController.pressDone))
    }
    
    
    var mainLabel: UILabel = {
        let label = UILabel()
        label.textColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.5)
        label.textAlignment = .left
        label.font = UIFont.boldSystemFont(ofSize: 13)
        return label
    }()
    
    var informationTextField: UITextField = {
        let textField = UITextField()
        textField.backgroundColor = .clear
        textField.textColor = UIColor(red: 0, green: 0, blue: 0, alpha: 1)
        textField.font = UIFont.systemFont(ofSize: 15)
        textField.textAlignment = .left
        return textField
    }()
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
           textField.resignFirstResponder();
           return true;
       }
    
    @objc func pressCancel() {
        presenter.pressedCancel()
    }
    
    @objc func pressDone() {
        presenter.pressedDone(with: informationTextField.text!)
    }
}

// MARK: - Extensions -

extension EditProfileItemViewController: EditProfileItemViewInterface {
    
    func setCurrentInformation(labelText: String, information: String) {
        mainLabel.text = labelText
        mainLabel.frame = CGRect(x: 15, y: 65, width: view.frame.width - 15, height: 30)
        view.addSubview(mainLabel)
        informationTextField.text = information
        informationTextField.frame = CGRect(x: 15, y: 85, width: view.frame.width - 15, height: 30)
        view.addSubview(informationTextField)
        informationTextField.delegate = self
        view.addSubview(SeperatorLineView(frame: CGRect(x: 0, y: 115, width: view.frame.width - 15, height: 1)))
    }
    
}
