//
//  PostPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 3/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class PostPresenter {

    // MARK: - Private properties -

    private unowned let view: PostViewInterface
    private let interactor: PostInteractorInterface
    private let wireframe: PostWireframeInterface
    var image: NSObject?
    // MARK: - Lifecycle -

    init(view: PostViewInterface, interactor: PostInteractorInterface, wireframe: PostWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PostPresenter: PostPresenterInterface {

    func viewLoaded() {
        view.setImage(with: image!)
    }
    func pressedShare(with image: NSObject, and caption: String) {
        interactor.createPost(with: image, and: caption)
    }
    func createdPost() {
        wireframe.routeToProfile()
    }
    func pressedBack() {
        wireframe.routeBack()
    }
}
