//
//  PostInteractor.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 3/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

class PostInteractor {
    var postService: PostService?
    var presenter: PostPresenter?
    var profileService: ProfileService?

    func updateNumberOfPosts() {
        profileService?.updateNumberOfPosts(forUID: User.current!.uid)
    }
}

// MARK: - Extensions -

extension PostInteractor: PostInteractorInterface {
    func createPost(with image: NSObject, and caption: String) {
        guard let user = User.current else {
            return
        }
        guard let uiImage = image as? UIImage else {
            return
        }
        postService?.create(for: uiImage,
                            with: caption,
                            by: user.username,
                            likeCount: 0,
                            completion: { [weak self] (bool) in
            if bool {
                self?.updateNumberOfPosts()
                self?.presenter?.createdPost()
            } else {
                assertionFailure()
            }
        })
    }
}
