//
//  PostWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 3/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class PostWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(with image: NSObject) {
        let moduleViewController = PostViewController()
        super.init(viewController: moduleViewController)

        let interactor = PostInteractor()
        interactor.postService = PostService()
        interactor.profileService = ProfileService()
        let presenter = PostPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        presenter.image = image
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension PostWireframe: PostWireframeInterface {
    func routeToProfile() {
        viewController.tabBarController?.selectedIndex = 4
        navigationController?.popViewController(animated: false)
    }
    func routeBack() {
        navigationController?.popViewController(animated: false)
    }
}
