//
//  SearchViewViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchViewViewController: ViewController {

    // MARK: - Public properties -

    var presenter: SearchViewPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Search"
        view.backgroundColor = .red
    }

}

// MARK: - Extensions -

extension SearchViewViewController: SearchViewViewInterface {
}
