//
//  HomeFeedWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class HomeFeedWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = HomeFeedViewController()
        super.init(viewController: moduleViewController)
        let interactor = HomeFeedInteractor()
        let presenter = HomeFeedPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        interactor.followService = FollowService()
        interactor.userService = UserService()
        interactor.likeService = LikeService()
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension HomeFeedWireframe: HomeFeedWireframeInterface {
    func routeToProfile(with uuid: String, isFollowed: Bool) {
        let wireframe = ProfileScreenWireframe(uuid: uuid)
        self.navigationController?.pushWireframe(wireframe)
    }

    func routeToLogIn() {
        let module = LoginWireframe()
        navigationController?.pushWireframeWithoutAnimation(module)
    }
}
