//
//  HomeFeedInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeFeedWireframeInterface: WireframeInterface {
}

protocol HomeFeedViewInterface: ViewInterface {
}

protocol HomeFeedPresenterInterface: PresenterInterface {
}

protocol HomeFeedInteractorInterface: InteractorInterface {
}
