//
//  AddPostPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AddPostPresenter {

    // MARK: - Private properties -

    private unowned let view: AddPostViewInterface
    private let interactor: AddPostInteractorInterface
    private let wireframe: AddPostWireframeInterface

    // MARK: - Lifecycle -

    init(view: AddPostViewInterface, interactor: AddPostInteractorInterface, wireframe: AddPostWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension AddPostPresenter: AddPostPresenterInterface {
}
