//
//  ActivityWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class ActivityWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ActivityViewController()
        super.init(viewController: moduleViewController)

        let interactor = ActivityInteractor()
        let presenter = ActivityPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        interactor.activityService = ActivityService()
        interactor.followService = FollowService()
        interactor.postService = PostService()
        interactor.userService = UserService()
        interactor.profileService = ProfileService()
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension ActivityWireframe: ActivityWireframeInterface {
    func transitionToProfile(with uuid: String) {
        navigationController?.pushWireframe(ProfileScreenWireframe(uuid: uuid))
    }

    func transitioToPost(with post: [Post]) {
        let viewController = ProfilePostViewController()
        viewController.postList = post
        navigationController?.pushViewController(viewController, animated: true)
    }
}
