//
//  AddPostInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AddPostWireframeInterface: WireframeInterface {
}

protocol AddPostViewInterface: ViewInterface {
}

protocol AddPostPresenterInterface: PresenterInterface {
}

protocol AddPostInteractorInterface: InteractorInterface {
}
