//
//  LoginWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = LoginViewController()
        super.init(viewController: moduleViewController)

        let interactor = LoginInteractor()
        let presenter = LoginPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LoginWireframe: LoginWireframeInterface {
   
    func transitionToNewUser() {
      let register = CreateUserWireframe()
        navigationController?.pushWireframeWithoutAnimation(register)
    }
    
    func transitionToProfile() {
        let tabBarWireframe = TabBarWireframe.init()
        navigationController?.setRootWireframeWithoutAnimation(tabBarWireframe)
    }
}
