//
//  LoginInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol LoginWireframeInterface: WireframeInterface {
    func transitionToProfile()
    func transitionToNewUser()
}

protocol LoginViewInterface: ViewInterface {
    func removeAllViews()
}

protocol LoginPresenterInterface: PresenterInterface {
    func pressedButton()
    func checkUser(user: FIRUser)
    func userExists()
    func transitionToNewUser()
}

protocol LoginInteractorInterface: InteractorInterface {
    func getUserState(user: FIRUser)
}
