//
//  LoginViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(topBar)
        view.backgroundColor = .white
        topBar.frame = CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height * 0.2)
    }
    
    var topBar: UIView = {
        let views = UIView(frame: .zero)
        views.backgroundColor = .red
        return views
    }()

}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}
