//
//  LoginPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class LoginPresenter {

    // MARK: - Private properties -

    private unowned let view: LoginViewInterface
    private let interactor: LoginInteractorInterface
    private let wireframe: LoginWireframeInterface

    // MARK: - Lifecycle -

    init(view: LoginViewInterface, interactor: LoginInteractorInterface, wireframe: LoginWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {
    func pressedButton() {
        view.setupFirebaseAuth()
        view.removeAllViews()
    }

    func checkUser(user: FIRUser) {
        interactor.getUserState(user: user)
    }

    func userExists() {
        wireframe.transitionToProfile()
    }

    func setupFirebaseAuth() {
    }

    func transitionToNewUser() {
        wireframe.transitionToNewUser()
    }
}
