//
//  ProfileScreenViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileScreenViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: ProfileScreenPresenterInterface!
    var profileImage: UIImage?
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Profile"
        self.navigationController?.isNavigationBarHidden = false
        self.navigationController?.navigationBar.backgroundColor = .red
        self.navigationController?.navigationBar.prefersLargeTitles = true
    }
    
    override func viewDidAppear(_ animated: Bool) {
        print(User.current?.username)
    }
    
    let profilePhoto: UIImageView = {
        let imageView = UIImageView()
        imageView.layer.cornerRadius = imageView.frame.size.width / 2;
        imageView.layer.masksToBounds = true
        return imageView
    }()
}

// MARK: - Extensions -

extension ProfileScreenViewController: ProfileScreenViewInterface {
}
