//
//  ProfileScreenViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileScreenViewController: ViewController {

    // MARK: - Public properties -

    var presenter: ProfileScreenPresenterInterface!

    // MARK: - Lifecycle -
   lazy var user = User.current
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .green
        navigationController?.navigationBar.prefersLargeTitles = true
    }
    override func viewDidAppear(_ animated: Bool) {
        print(user?.username)

    }

}

// MARK: - Extensions -

extension ProfileScreenViewController: ProfileScreenViewInterface {
}
