//
//  ProfileScreenPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ProfileScreenPresenter {

    // MARK: - Private properties -

    private unowned let view: ProfileScreenViewInterface
    private let interactor: ProfileScreenInteractorInterface
    private let wireframe: ProfileScreenWireframeInterface

    // MARK: - Lifecycle -

    init(view: ProfileScreenViewInterface, interactor: ProfileScreenInteractorInterface, wireframe: ProfileScreenWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ProfileScreenPresenter: ProfileScreenPresenterInterface {
}
