//
//  HomeFeedViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PostTableViewDelegate: class {
    func clickedUsername(with username: String)
    func didTapLikeButton(_ likeButton: UIButton, on cell: PostTableCell)
}

class PostTableView: UITableView {

    // MARK: - Public properties -
    var tableView = UITableView()
    var postList: [Post]?
    weak var tableViewDelegate: PostTableViewDelegate?
    // MARK: - Lifecycle -

    override init(frame: CGRect, style: UITableView.Style) {
        super.init(frame: frame, style: style)
        register(PostTableCell.self, forCellReuseIdentifier: "TableViewCell")
        rowHeight = frame.width + 201
        dataSource = self
        delegate = self
        allowsSelection = false
        backgroundColor = UIColor(rgb: 0xFAFAFA)
    }

    convenience init(frame: CGRect, style: UITableView.Style, posts: [Post]) {
        self.init(frame: frame, style: style)
        self.postList = posts
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func updateWithPostsList(posts: [Post]) {
        postList = posts
        self.reloadData()
    }

    @objc func pressedOnUsername(sender: Any) {
        guard let button = sender as? UsernameButton else {
            return
        }
        let name: String = button.username!
        tableViewDelegate?.clickedUsername(with: name)
    }
}

// MARK: - Extensions -
extension PostTableView: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return postList?.count ?? 9
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let myCell = tableView.dequeueReusableCell(withIdentifier: PostTableCell.identifier,
                                                   for: indexPath) as? PostTableCell
        guard let cell = myCell else {
            return UITableViewCell()
        }

        if let posts = postList {
            cell.shimmerView.removeFromSuperview()
            cell.shimmerView.stopShimmeringEffect()
            cell.contentView.isUserInteractionEnabled = false
            cell.frame.size = frame.size

            let slice = posts[indexPath.row]
            cell.setupProfileImage(info: slice)
            cell.setupTopNameButton(name: slice.poster)
            cell.setupMainImageView(imageURL: slice.imageURL)
            cell.setupLikeButton(isLiked: slice.isLiked)
            cell.delegate = self
            if !slice.caption.isEmpty {
                cell.setupBottonNameButton(name: slice.poster)
                cell.setupCaptionLabel(caption: slice.caption)
                cell.setupDateLabel(date: slice.creationDate, captionExists: true)
            } else {
                cell.setupDateLabel(date: slice.creationDate, captionExists: false)
            }
            cell.backgroundColor = .white
            cell.setupLikeLabel(with: String(slice.likeCount))
            cell.topNameButton.tag = indexPath.row
            cell.bottomNameButton.tag = indexPath.row
            cell.topNameButton.addTarget(self, action: #selector(pressedOnUsername(sender:)), for: .touchDown)
            cell.bottomNameButton.addTarget(self, action: #selector(pressedOnUsername(sender:)), for: .touchDown)
        } else {
            cell.shimmerView.backgroundColor = UIColor(rgb: 0xEDEDED)
            cell.shimmerView.startShimmeringEffect()
        }
        cell.backgroundColor = UIColor(rgb: 0xFAFAFA)
        return cell
    }
}

extension PostTableView: PostActionCellDelegate {
    func didTapLikeButton(_ likeButton: UIButton, on cell: PostTableCell) {
        tableViewDelegate?.didTapLikeButton(likeButton, on: cell)
    }
}
