//
//  AddPostWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class AddPostWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = AddPostViewController(collectionViewLayout: UICollectionViewFlowLayout())
        super.init(viewController: moduleViewController)

        let interactor = AddPostInteractor()
        
        let presenter = AddPostPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension AddPostWireframe: AddPostWireframeInterface {
    func routeBack() {
        viewController.tabBarController?.tabBar.isHidden = false 
        viewController.tabBarController?.selectedIndex = 4
    }
    
    func routeToPost(with image: NSObject) {
        let wireframe = PostWireframe(with: image)
        navigationController?.pushWireframe(wireframe)
    }
}
