//
//  AddPostInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Photos

protocol AddPostWireframeInterface: WireframeInterface {
    func routeBack()
    func routeToPost(with image: NSObject)
}

protocol AddPostViewInterface: ViewInterface {
}

protocol AddPostPresenterInterface: PresenterInterface {
    var postList: [PHAsset]? {get}
    func viewLoaded()
    func pressedCancel()
    func pressedNext(with image: NSObject)
    func imageLoaded(with asset: PHAsset, size: CGSize, completion: @escaping (NSObject) -> Void)
}

protocol AddPostInteractorInterface: InteractorInterface {
    func requestImages() -> [PHAsset]
    func getSpecificImage(with asset: PHAsset, size: CGSize, completion: @escaping (NSObject) -> Void)
}
