//
//  AddPostInteractor.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Photos

class AddPostInteractor {
    var presenter: AddPostPresenterInterface?
}

// MARK: - Extensions -

extension AddPostInteractor: AddPostInteractorInterface {
    func requestImages() -> [PHAsset] {
        var postList = [PHAsset]()

        let assets = PHAsset.fetchAssets(with: PHAssetMediaType.image, options: nil)
        assets.enumerateObjects({ (object, _, _) in
            postList.append(object)
        })

        postList.reverse()
        return postList
    }

    func getSpecificImage(with asset: PHAsset, size: CGSize, completion: @escaping (NSObject) -> Void) {
        let manager = PHImageManager.default()
        manager.requestImage(for: asset,
                             targetSize: size,
                             contentMode: .aspectFill,
                             options: nil) { (result, _) in
            DispatchQueue.main.async {
                if let result = result {
                   completion(result as NSObject)
                } else {
                    fatalError()
                }
            }
        }
    }
}
