//
//  AddPostPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Photos

class AddPostPresenter {

    // MARK: - Private properties -

    private unowned let view: AddPostViewInterface
    private let interactor: AddPostInteractorInterface
    private let wireframe: AddPostWireframeInterface
    var postList: [PHAsset]?

    // MARK: - Lifecycle -

    init(view: AddPostViewInterface, interactor: AddPostInteractorInterface, wireframe: AddPostWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension AddPostPresenter: AddPostPresenterInterface {

    func viewLoaded() {
        postList = interactor.requestImages()
    }

    func pressedCancel() {
        wireframe.routeBack()
    }

    func pressedNext(with image: NSObject) {
        wireframe.routeToPost(with: image)
    }

    func imageLoaded(with asset: PHAsset, size: CGSize, completion: @escaping (NSObject) -> Void) {
        interactor.getSpecificImage(with: asset, size: size, completion: { (result) in
            completion(result)
        })
    }
}
