//
//  EditProfileInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 22.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EditProfileWireframeInterface: WireframeInterface {
    func routeToEditItem(with item: FormItems, userInformation: UserInformation, delegate: EditProfileItemDelegate)
    func viewDisappeared()
}

protocol EditProfileViewInterface: ViewInterface {
    func updateProfileForm(info: UserInformation)
    func removeAllViews()
    func addProfileInformationForm(userInformation: UserInformation)
}

protocol EditProfilePresenterInterface: PresenterInterface {
    func pressedOn(label item: FormItems)
    func pressedDone()
    func pressedCancel()
    func viewDisappeared()
    func recievedInformation(info: UserInformation)
    func viewLoaded()
    func updateProfilePhoto(image: NSObject)
}

protocol EditProfileInteractorInterface: InteractorInterface {
    func getUserInformation()
    func updateUsersInformation(info: UserInformation)
    func updateProfilePhoto(image: NSObject)
}
