//
//  EditProfileInteractor.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 22.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EditProfileInteractor {
}

// MARK: - Extensions -

extension EditProfileInteractor: EditProfileInteractorInterface {
    func updateUsersInformation(info: UserInformation) {
        
    }
}
