//
//  EditProfileWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 22.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EditProfileWireframe: BaseWireframe {

    // MARK: - Private properties -
    // MARK: - Module setup -

    init(userInformation: UserInformation, delegate: EditProfileDelegate?)  {
        let moduleViewController = EditProfileViewController()
        moduleViewController.userInformation = userInformation
        super.init(viewController: moduleViewController)

        let interactor = EditProfileInteractor()
        let presenter = EditProfilePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        presenter.delegate = delegate
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension EditProfileWireframe: EditProfileWireframeInterface {
    func routeToEditProfileItem(with item: FormItems, userInformation: UserInformation, delegate: EditProfileItemDelegate){
        let module = EditProfileItemWireframe(item: item, userInformation: userInformation, delegate: delegate)
        navigationController?.pushWireframeWithoutAnimation(module)
    }
    
    func viewDisappeared() {
        navigationController?.popViewController(animated: false)
    }
}
