//
//  EditProfileInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 22.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EditProfileWireframeInterface: WireframeInterface {
    func routeToEditProfileItem(with item: FormItems, userInformation: UserInformation, delegate: EditProfileItemDelegate)
    func viewDisappeared()
}

protocol EditProfileViewInterface: ViewInterface {
    func updateProfileForm(info: UserInformation)
}

protocol EditProfilePresenterInterface: PresenterInterface {
    func pressedOn(label item: FormItems, userInformation: UserInformation)
    func pressedDone(info: UserInformation)
    func pressedCancel()
}

protocol EditProfileInteractorInterface: InteractorInterface {
    func updateUsersInformation(info: UserInformation)
}
