//
//  ProfileScreenWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class ProfileScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(uuid: String) {
        let moduleViewController = ProfileScreenViewController(collectionViewLayout: UICollectionViewFlowLayout())
        super.init(viewController: moduleViewController)
        let interactor = ProfileScreenInteractor()
        let presenter = ProfileScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.followService = FollowService()
        interactor.postService = PostService()
        interactor.userService = UserService()
        interactor.profileService = ProfileService()
        presenter.uuid = uuid
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ProfileScreenWireframe: ProfileScreenWireframeInterface {
    func routeToEdit(delegate: EditProfileDelegate, image: String) {
        let module = EditProfileWireframe(delegate: delegate, image: image)
        navigationController?.pushWireframe(module)
    }
    
    func routeToSettings() {
        let module = ProfileSettingsWireframe()
        navigationController?.pushWireframeWithoutAnimation(module)
    }
    
    func routeToLogIn() {
        let module = LoginWireframe()
        navigationController?.pushWireframeWithoutAnimation(module)
    }
}
