//
//  ProfileScreenInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileScreenWireframeInterface: WireframeInterface {
    func routeToEdit(delegate: EditProfileDelegate, image: String)
    func routeToSettings()
    func routeToLogIn()
}

protocol ProfileScreenViewInterface: ViewInterface {
    func updateProfileForm(info: UserInformation)
    func setupProfilePhoto(with image: String)
    func setupUserStatisticView(with info: UserStatistics)
    func setupEditProfileButton()
    func updatePosts()
}

protocol ProfileScreenPresenterInterface: PresenterInterface {
    var isEditHidden: Bool { get set}
    var uuid: String { get set}
    var postList: [Post]? { get set }
    func buttonLoaded(completion: @escaping (Bool) -> Void)
    func pressedEdit()
    func pressedFollow(isFollowing: Bool, username: String)
    func viewReloaded()
    func selectedMenuItem(with selection: Menu)
    func headerViewExists()
    func recievedPosts(posts: [Post])
    func recievedProfileImage(with imageURL: String)
    func recievedUserInformation(info: UserInformation)
    func recieveUserStatistics(statistics: UserStatistics)
}

protocol ProfileScreenInteractorInterface: InteractorInterface {
    func getUserInformation(with uuid: String)
    func getUserPosts(with uuid: String)
    func getProfilePhoto(with uuid: String)
    func getUserStatistics(with uuid: String)
    func checkIfFollowing(with uuid: String, completion: @escaping (Bool) -> Void)
    func setFollowing(isFollowing: Bool, username: String)
}
