//
//  ProfileScreenInteractor.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class ProfileScreenInteractor {
    var presenter: ProfileScreenPresenter?
    var followService: FollowService?
    var postService: PostService?
    var userService: UserService?
    var profileService: ProfileService?
}

// MARK: - Extensions -

extension ProfileScreenInteractor: ProfileScreenInteractorInterface {

    func getUserInformation(with uuid: String) {
        profileService?.userInformation(for: uuid, completion: { [weak self]  (info) in
            self?.presenter?.recievedUserInformation(info: info)
        })
    }

    func checkIfFollowing(with uuid: String, completion: @escaping (Bool) -> Void) {
        followService?.isUserFollowed(uuid, byCurrentUserWithCompletion: { (isFollowed) in
            completion(isFollowed)
        })
    }

    func getUserPosts(with uuid: String) {
        profileService?.posts(for: uuid) { [weak self] (posts) in
            self?.presenter?.recievedPosts(posts: posts)
        }
    }

    func getUserStatistics(with uuid: String) {
        followService?.getNumberOfFollowersAndFollowing(from: uuid, completion: { [weak self] (follower, following) in
            self?.profileService?.getNumberOfPost(for: uuid, completion: { (postCount) in
                self?.presenter?.recieveUserStatistics(statistics: UserStatistics(postCount: Int(postCount)!,
                                                                                  followerCount: follower,
                                                                                  followingCount: following))
            })
        })
    }

    func getProfilePhoto(with uuid: String) {
        profileService?.profileImage(for: uuid) { (imageURL) in
            self.presenter?.recievedProfileImage(with: imageURL)
        }
    }

    func setFollowing(isFollowing: Bool, username: String) {
        followService?.setIsFollowing(!isFollowing, fromCurrentUserTo: username)
    }
}
