//
//  ProfileScreenPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ProfileScreenPresenter: EditProfileDelegate {

    // MARK: - Private properties -

    private unowned let view: ProfileScreenViewInterface
    private let interactor: ProfileScreenInteractorInterface
    private let wireframe: ProfileScreenWireframeInterface

    // MARK: - Lifecycle -

    init(view: ProfileScreenViewInterface, interactor: ProfileScreenInteractorInterface, wireframe: ProfileScreenWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ProfileScreenPresenter: ProfileScreenPresenterInterface {
    func pressedEdit(userInformation: UserInformation) {
        wireframe.routeToEdit(userInformation: userInformation, delegate: self)
    }
}
extension ProfileScreenPresenter: EditProfileItemDelegate {
    func recieveNewData(updatedUserInformation: UserInformation) {
        view.updateProfileForm(info: updatedUserInformation)
        
    }
    
    
}
