//
//  ProfileScreenWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ProfileScreenViewController()
        super.init(viewController: moduleViewController)

        let interactor = ProfileScreenInteractor()
        let presenter = ProfileScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ProfileScreenWireframe: ProfileScreenWireframeInterface {
    func routeToEdit(userInformation: UserInformation, delegate: EditProfileDelegate) {
        let module = EditProfileWireframe(userInformation: userInformation, delegate: delegate)
        navigationController?.pushWireframeWithoutAnimation(module)
    }
}
