//
//  ProfileScreenInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileScreenWireframeInterface: WireframeInterface {
    func routeToEdit(userInformation: UserInformation, delegate: EditProfileDelegate)
}

protocol ProfileScreenViewInterface: ViewInterface {
    func updateProfileForm(info: UserInformation)
}

protocol ProfileScreenPresenterInterface: PresenterInterface {
    func pressedEdit(userInformation: UserInformation)
}

protocol ProfileScreenInteractorInterface: InteractorInterface {
}
