//
//  CreateUsernameViewInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 11.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CreateUsernameViewWireframeInterface: WireframeInterface {
}

protocol CreateUsernameViewViewInterface: ViewInterface {
}

protocol CreateUsernameViewPresenterInterface: PresenterInterface {
}

protocol CreateUsernameViewInteractorInterface: InteractorInterface {
}
