//
//  CreateUsernameViewViewController.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 11.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateUsernameViewViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CreateUsernameViewPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension CreateUsernameViewViewController: CreateUsernameViewViewInterface {
}
