//
//  CreateUsernameViewWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 11.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateUsernameViewWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = CreateUsernameViewViewController()
        super.init(viewController: moduleViewController)

        let interactor = CreateUsernameViewInteractor()
        let presenter = CreateUsernameViewPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CreateUsernameViewWireframe: CreateUsernameViewWireframeInterface {
}
