//
//  CreateUsernameViewPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 11.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CreateUsernameViewPresenter {

    // MARK: - Private properties -

    private unowned let view: CreateUsernameViewViewInterface
    private let interactor: CreateUsernameViewInteractorInterface
    private let wireframe: CreateUsernameViewWireframeInterface

    // MARK: - Lifecycle -

    init(view: CreateUsernameViewViewInterface, interactor: CreateUsernameViewInteractorInterface, wireframe: CreateUsernameViewWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CreateUsernameViewPresenter: CreateUsernameViewPresenterInterface {
}
