//
//  CreateUserWireframe.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 12.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateUserWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = CreateUserViewController()
        super.init(viewController: moduleViewController)

        let interactor = CreateUserInteractor()
        let presenter = CreateUserPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CreateUserWireframe: CreateUserWireframeInterface {
    func transitionToProfile() {
        navigationController?.popToRootViewController(animated: false)
    }
}
