//
//  CreateUserInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 12.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CreateUserWireframeInterface: WireframeInterface {
    func transitionToProfile()
}

protocol CreateUserViewInterface: ViewInterface {
}

protocol CreateUserPresenterInterface: PresenterInterface {
    func buttonPressed(username: String?)
    func transitionToProfile()
}

protocol CreateUserInteractorInterface: InteractorInterface {
    func createUser(username: String?)
}
