//
//  HomeFeedPresenter.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeFeedPresenter {

    // MARK: - Private properties -

    private unowned let view: HomeFeedViewInterface
    private let interactor: HomeFeedInteractorInterface
    private let wireframe: HomeFeedWireframeInterface

    // MARK: - Lifecycle -

    init(view: HomeFeedViewInterface, interactor: HomeFeedInteractorInterface, wireframe: HomeFeedWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HomeFeedPresenter: HomeFeedPresenterInterface {
}
