//
//  SignUpInterfaces.swift
//  PortfolioSocial
//
//  Created by Peter Shaburov on 07.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SignUpWireframeInterface: WireframeInterface {
}

protocol SignUpViewInterface: ViewInterface {
}

protocol SignUpPresenterInterface: PresenterInterface {
}

protocol SignUpInteractorInterface: InteractorInterface {
}
